### ISSUE TITLE
Backup fails for GitLab projects without repository

### ISSUE THREAD

**Issue by mburtscher** [fusonic/git-backup#1]
Something seems to have changed in GitLab: Project can now be created without a repository. This is the case for our [fusonic/playground/fmh/neighborhoodcheck/test-access project](https://gitlab.com/fusonic/playground/fmh18/neighbourhoodcheck/test-access).

Backup now fails with the following error:

```
remote: A repository for this project does not exist yet.
fatal: repository 'https://gitlab-ci-token@gitlab.com/fusonic/playground/fmh18/neighbourhoodcheck/test-access.git/' not found
```

There is no existing folder for this project in the backup directory. So it seems that it was handled correctly earlier.

**Comment by mburtscher** [comment]
@davidroth Do you have time to have a look at this?

**Comment by davidroth** [comment]
Dunno what caused this.
Deleted the test-access project because it was empty/unused.

**Comment by mburtscher** [comment]
OK, let's see if it happens for other projects without repo as well...
